import { StyleSheet } from 'react-native';

import { styleConstants as sc } from 'shared/styleConstants';

export const adminModalStyles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  container: {
    width: '90%',
    height: '90%',
    backgroundColor: sc.colors.overlayOnRed,
    borderWidth: 2,
    borderColor: sc.colors.gold,
    borderRadius: sc.borderRadius.md,
    padding: sc.size.lg,
    flexDirection: 'column',
  },
  content: {
    flex: 1,
    flexDirection: 'column',
  },
  footer: {
    alignItems: 'center',
    paddingTop: sc.size.lg,
  },
  closeButton: {
    backgroundColor: '#8B4513',
    borderWidth: 2,
    borderColor: sc.colors.gold,
    minWidth: 100,
    paddingHorizontal: sc.size.lg,
    paddingVertical: sc.size.base,
  },
  navRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: sc.size.md,
    borderBottomWidth: 2,
    borderBottomColor: sc.colors.gold,
  },
  navButton: {
    backgroundColor: '#8B4513',
    paddingVertical: sc.size.base,
    paddingHorizontal: sc.size.md,
    borderRadius: sc.borderRadius.base,
    minWidth: 80,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: sc.colors.gold,
    marginBottom: 0,
  },
  navButtonSelected: {
    borderColor: '#FF8C00',
    borderWidth: 3,
  },
  navButtonText: {
    color: sc.colors.text,
    fontSize: sc.fontSizes.sm,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  contentArea: {
    flex: 1,
    width: '95%',
    height: '95%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: sc.colors.green,
    borderRadius: sc.borderRadius.md,
    padding: sc.size.lg,
  },
  sectionTitle: {
    fontSize: sc.fontSizes.xl,
    fontWeight: 'bold',
    color: sc.colors.gold,
    textAlign: 'center',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: sc.size.md,
    width: '100%',
    marginBottom: sc.size.lg,
  },
  searchInputContainer: {
  },
  searchInputCustom: {
    container: {
      width: '40%',
    },
  },
  searchButton: {
    backgroundColor: '#8B4513',
    borderWidth: 2,
    borderColor: sc.colors.gold,
    minWidth: 80,
    height: 44,
    paddingHorizontal: sc.size.lg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: sc.colors.danger,
    fontSize: sc.fontSizes.sm,
    textAlign: 'left',
    marginTop: sc.size.sm,
    backgroundColor: sc.colors.dangerAlpha10,
    padding: sc.size.sm,
    borderRadius: sc.borderRadius.sm,
  },
  playerDataContainer: {
    backgroundColor: sc.colors.overlayOnRed,
    borderRadius: sc.borderRadius.md,
    padding: sc.size.lg,
    marginTop: sc.size.lg,
    borderWidth: 1,
    borderColor: sc.colors.gold,
    width: '100%',
  },
  playerDataTitle: {
    fontSize: sc.fontSizes.lg,
    fontWeight: 'bold',
    color: sc.colors.gold,
    textAlign: 'center',
    marginBottom: sc.size.lg,
  },
  playerDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: sc.size.md,
  },
  playerDataLabel: {
    fontSize: sc.fontSizes.md,
    fontWeight: 'bold',
    color: sc.colors.text,
    flex: 1,
  },
  playerDataValue: {
    fontSize: sc.fontSizes.md,
    color: sc.colors.textSecondary,
    flex: 2,
    textAlign: 'right',
  },
  creditContainer: {
    backgroundColor: sc.colors.overlayOnRed,
    borderRadius: sc.borderRadius.md,
    padding: sc.size.lg,
    marginTop: sc.size.lg,
    borderWidth: 1,
    borderColor: sc.colors.gold,
    width: '100%',
    alignItems: 'center',
  },
  creditTitle: {
    fontSize: sc.fontSizes.lg,
    fontWeight: 'bold',
    color: sc.colors.gold,
    textAlign: 'center',
    marginBottom: sc.size.lg,
  },
  creditButtonsGrid: {
    width: '100%',
    marginBottom: sc.size.lg,
  },
  creditButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: sc.size.md,
  },
  creditAmountButton: {
    backgroundColor: '#8B4513',
    borderWidth: 2,
    borderColor: sc.colors.gold,
    minWidth: 80,
    paddingHorizontal: sc.size.md,
    paddingVertical: sc.size.sm,
  },
  creditSubmitButton: {
    backgroundColor: sc.colors.success,
    borderWidth: 2,
    borderColor: sc.colors.gold,
    minWidth: 150,
    paddingHorizontal: sc.size.xl,
    paddingVertical: sc.size.md,
  },
  creditSubmitButtonDisabled: {
    backgroundColor: '#666',
    borderColor: '#999',
    opacity: 0.5,
  },
  clearPlayerButton: {
    backgroundColor: sc.colors.danger,
    borderWidth: 2,
    borderColor: sc.colors.gold,
    minWidth: 120,
    paddingHorizontal: sc.size.lg,
    paddingVertical: sc.size.sm,
    marginTop: sc.size.md,
  },
  activityTableContainer: {
    backgroundColor: sc.colors.overlayOnRed,
    borderRadius: sc.borderRadius.md,
    padding: sc.size.lg,
    marginTop: sc.size.lg,
    borderWidth: 1,
    borderColor: sc.colors.gold,
    width: '100%',
    height: '60%',
    flexDirection: 'column',
  },
  activityTableTitle: {
    fontSize: sc.fontSizes.lg,
    fontWeight: 'bold',
    color: sc.colors.gold,
    textAlign: 'center',
    marginBottom: sc.size.lg,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: sc.colors.gold,
    paddingVertical: sc.size.sm,
    borderRadius: sc.borderRadius.sm,
    marginBottom: sc.size.sm,
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: sc.fontSizes.xs,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    paddingHorizontal: 2,
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: sc.colors.green,
    paddingVertical: sc.size.sm,
    marginBottom: 1,
    borderRadius: sc.borderRadius.sm,
  },
  tableCell: {
    flex: 1,
    fontSize: sc.fontSizes.xs,
    color: sc.colors.text,
    textAlign: 'center',
    paddingHorizontal: 2,
  },
  closeButtonInline: {
    backgroundColor: '#8B4513',
    borderWidth: 2,
    borderColor: sc.colors.gold,
    minWidth: 80,
    height: 44,
    paddingHorizontal: sc.size.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tableScrollView: {
    flex: 1,
    width: '100%',
  },
  tableScrollContent: {
    flexGrow: 1,
  },
});